2021/07/25
INSERT INTO `workout_plan` (`workout_plan_id`, `workout_plan_name`, `duration`, `workout_desc`, `workout_bmi_category,`, `workout_monday`, `workout_tuesday`, `workout_wednesday`, `workout_thursday`, `workout_friday`, `workout_saturday`, `workout_sunday`, `exerises_set_id`, `created_at`, `updated_at`) VALUES (NULL, 'WorkoutPlan A', '3', 'This is Workout Plan A', 'Underweight', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', '0', current_timestamp(), current_timestamp()), (NULL, 'WorkoutPlan B', '2', 'This is Workout Plan B', 'Healthy weight', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', '0', current_timestamp(), current_timestamp());
INSERT INTO `workout_plan` (`workout_plan_id`, `workout_plan_name`, `duration`, `workout_desc`, `workout_bmi_category,`, `workout_monday`, `workout_tuesday`, `workout_wednesday`, `workout_thursday`, `workout_friday`, `workout_saturday`, `workout_sunday`, `exerises_set_id`, `created_at`, `updated_at`) VALUES (NULL, 'WorkoutPlan C', '3', 'This is Workout Plan C', 'Overweight', 'no', 'yes', 'no', 'yes', 'yes', 'no', 'yes', '0', '2021-07-25 17:03:01', '2021-07-25 17:03:01');
INSERT INTO `workout_plan` (`workout_plan_id`, `workout_plan_name`, `duration`, `workout_desc`, `workout_bmi_category,`, `workout_monday`, `workout_tuesday`, `workout_wednesday`, `workout_thursday`, `workout_friday`, `workout_saturday`, `workout_sunday`, `exerises_set_id`, `created_at`, `updated_at`) VALUES (NULL, 'WorkoutPlan D', '4', 'This is Workout Plan D', 'Obesity', 'no', 'yes', 'no', 'yes', 'yes', 'no', 'yes', '0', '2021-07-25 17:03:01', '2021-07-25 17:03:01');

INSERT INTO `diet_plan` (`diet_plan_id`, `diet_plan_name`, `bmi_category`, `breakfast`, `lunch`, `dinner`, `diet_desc`, `diet_monday`, `diet_tuesday`, `diet_wednesday`, `diet_thursday`, `diet_friday`, `diet_saturday`, `diet_sunday`, `created_at`, `updated_at`) VALUES (NULL, 'Diet Plan A', 'Underweight', '1 cup skim milk', 'cheddar', 'grilled salmon', 'Diets for Weight Loss', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', current_timestamp(), current_timestamp());
INSERT INTO `diet_plan` (`diet_plan_id`, `diet_plan_name`, `bmi_category`, `breakfast`, `lunch`, `dinner`, `diet_desc`, `diet_monday`, `diet_tuesday`, `diet_wednesday`, `diet_thursday`, `diet_friday`, `diet_saturday`, `diet_sunday`, `created_at`, `updated_at`) VALUES (NULL, 'Diet Plan C', 'Overweight', '2 cup skim milk', 'cheddar', 'grilled salmon', 'Diets for Overwieight', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', '2021-07-25 19:09:37', '2021-07-25 19:09:37');
INSERT INTO `diet_plan` (`diet_plan_id`, `diet_plan_name`, `bmi_category`, `breakfast`, `lunch`, `dinner`, `diet_desc`, `diet_monday`, `diet_tuesday`, `diet_wednesday`, `diet_thursday`, `diet_friday`, `diet_saturday`, `diet_sunday`, `created_at`, `updated_at`) VALUES (NULL, 'Diet Plan D', 'Obesity', '5 cup skim milk', 'cheddar', 'grilled salmon', 'Diets for Obesity', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', '2021-07-25 19:09:37', '2021-07-25 19:09:37');

INSERT INTO `appointment` (`appointment_id`, `time_slot`, `appointment_date`, `current_height`, `current_weight`, `bmi`, `bmi_type`, `uid`, `diet_plan_id`, `workout_plan_id`, `created_at`, `updated_at`) VALUES (NULL, '7-9', '2021-07-25', '197', '63', '22.12', 'Healthy weight', '1', '1', '1', current_timestamp(), current_timestamp());
INSERT INTO `appointment` (`appointment_id`, `time_slot`, `appointment_date`, `current_height`, `current_weight`, `bmi`, `bmi_type`, `uid`, `diet_plan_id`, `workout_plan_id`, `created_at`, `updated_at`) VALUES (NULL, '9-11', '2021-07-24', '170', '63', '25.5', 'Overweight', '2', '4', '3', '2021-07-25 19:15:10', '2021-07-25 19:15:10');
INSERT INTO `appointment` (`appointment_id`, `time_slot`, `appointment_date`, `current_height`, `current_weight`, `bmi`, `bmi_type`, `uid`, `diet_plan_id`, `workout_plan_id`, `created_at`, `updated_at`) VALUES (NULL, '13-15', '2021-07-23', '170', '63', '30.0', 'Obesity', '4', '5', '4', '2021-07-25 19:15:10', '2021-07-25 19:15:10');
